### ISSUE TITLE
RightClick crash

### ISSUE THREAD

**Issue by steve823** [crystalidea/anytoiso-public#33] opened 2020-08-31 17:14 UTC
Using version 3.9.6 Pro with Windows ver 2004, build 19041.450 when I use the mouse Right Click causes the explorer window to close. Using the keyboard windows "menu" key also caused it to close.

**Comment by kleuter** [comment] 2020-09-02 10:38
Did you try to disable the shell integration in the app Preferences?

**Comment by kleuter** [comment] 2022-02-19 20:58
Caused by the NVIDIA shell extension, imroved in 4.0

**Comment by kleuter** [comment] 2024-01-29 14:20
Fixed in the latest version

**Closed by kleuter** 2024-01-29 14:20 UTC
Labels: bug
